# Generated by Django 4.2.1 on 2023-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MisMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('datetime', models.DateField()),
                ('filename', models.ImageField(upload_to='')),
            ],
        ),
    ]
