# Generated by Django 4.2.1 on 2023-07-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_flatpageadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
