# Generated by Django 4.2.1 on 2023-07-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mismovie',
            name='filename',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
