# Generated by Django 4.2.1 on 2023-07-25 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0004_alter_mismovie_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='mismovie',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mismovie',
            name='filename',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
